version: '3.8'

services:
  database:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: de-prueba
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - db_data:/var/lib/postgresql/data

  python_app:
    build: .
    depends_on:
      - database

    environment:
      - DATABASE_URL=postgresql://root:root@database:5432/de-prueba

volumes:
  db_data:
